# Generated by Django 3.2.25 on 2025-09-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='source',
        ),
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='bus',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Travel.tour'),
            preserve_default=False,
        ),
    ]
